### PR TITLE
Resolve issue devkitPro/3ds-examples#2

### PR DESCRIPTION
**Pull request by feeddageek**

### CODE REVIEW

**Comment by fincs** [comment]
The graphics/bitmap/24bit-color example was deliberately left out from the autobuilding Makefiles because it depends on imagemagick and that renders it uncompilable with out-of-the-box devkitARM. Please revert any changes you did to that example.

**Comment by feeddageek** [comment]
I suspected it might have been the case, but I included them just in case.
Is the rest of the patch OK, or was the exclusion of audio, network and time intentional for some other reason i did not think about ?

**Comment by fincs** [comment]
The rest is OK.

**Comment by WinterMute** [comment]
I actually have commits waiting to push which basically include these changes, sorry. Currently still tidying up one of the other examples.

If you separate the changes to the camera example I'll merge that though.

**Comment by feeddageek** [comment]
My master is now clean of any changes apart from those related to the camera example.

**Pull request closed without merging**
